Trying to get the PR another way

diff --git a/pr-info-from-workflow-run/action.yaml b/pr-info-from-workflow-run/action.yaml
--- a/pr-info-from-workflow-run/action.yaml
+++ b/pr-info-from-workflow-run/action.yaml
@@ -29,19 +29,27 @@ runs:
       shell: bash
       id: extract
       run: |
-        PR_NUMBER=$(jq -r '.workflow_run.pull_requests[0].number' "$GITHUB_EVENT_PATH")
         HEAD_SHA=$(jq -r '.workflow_run.head_commit.id' "$GITHUB_EVENT_PATH")
-        #PR_TITLE=$(jq -r '.workflow_run.pull_requests[0].title' "$GITHUB_EVENT_PATH")
-        #PR_BODY=$(jq -r '.workflow_run.pull_requests[0].body' "$GITHUB_EVENT_PATH")
-        #PR_AUTHOR=$(jq -r '.workflow_run.pull_requests[0].user.login' "$GITHUB_EVENT_PATH")
+        echo "pr-headsha=$HEAD_SHA" | tee -a "$GITHUB_OUTPUT"
 
-        echo "pr-number=$PR_NUMBER" | tee -a $GITHUB_OUTPUT
-        echo "pr-headsha=$HEAD_SHA" | tee -a $GITHUB_OUTPUT
-        #echo "pr-title=$PR_TITLE" | tee -a $GITHUB_OUTPUT
+        # get the PR number from PRs with this HEAD_SHA
+        API_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/commits/${HEAD_SHA}/pulls"
+        RESPONSE=$(curl -L \
+                    -H "Accept: application/vnd.github+json" \
+                    -H "Authorization: Bearer $GITHUB_TOKEN" \
+                    -H "X-GitHub-Api-Version: 2022-11-28" \
+                    $API_URL)
+        echo "API response: $RESPONSE"  # TODO DEBUG
+        MATCHING_PRS=$(echo "$RESPONSE" | jq --arg sha "$HEAD_SHA" '[.[] | select(.head.sha == $sha)]')
+        COUNT=$(echo "$MATCHING_PRS" | jq 'length')
 
-        # The body of the PR can be multiline, so we wrap it <<EOF
-        #echo "pr-body<<EOF" | tee -a $GITHUB_OUTPUT
-        #echo "$PR_BODY" | tee -a $GITHUB_OUTPUT
-        #echo "EOF" | tee -a $GITHUB_OUTPUT
-
-        #echo "pr-author=$PR_AUTHOR" | tee -a $GITHUB_OUTPUT
+        if [ "$COUNT" -eq 0 ]; then
+          echo "No pull request found associated with HEAD_SHA: ${HEAD_SHA}" >&2
+          exit 1
+        elif [ "$COUNT" -eq 1 ]; then
+          PR_NUMBER=$(echo "$MATCHING_PRS" | jq -r '.[0].number')
+          echo "pr-number=$PR_NUMBER" | tee -a "$GITHUB_OUTPUT"
+        else
+          echo "Error: Multiple pull requests found with HEAD_SHA ${HEAD_SHA}. Unable to determine the correct PR." >&2
+          exit 1
+        fi
